### ISSUE TITLE
AppVeyor build failed

### ISSUE THREAD

**Issue by qfox** [bem/bem-sdk#209]
```
./node_modules/.bin/lerna bootstrap -- --force
lerna info version 2.0.0
lerna info versioning independent
lerna info Bootstrapping 14 packages
lerna info lifecycle preinstall
lerna WARN EHOIST_ROOT_VERSION The repository root depends on chai@^4.0.2, which differs from the more common chai@^3.5.0.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.deps" package depends on chai@^3.5.0, which differs from the hoisted chai@^4.0.2.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.fs-scheme" package depends on chai@^3.5.0, which differs from the hoisted chai@^4.0.2.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.graph" package depends on chai@^3.5.0, which differs from the hoisted chai@^4.0.2.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.import-notation" package depends on chai@^3.5.0, which differs from the hoisted chai@^4.0.2.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on mocha@^3.4.2, which differs from the more common mocha@^3.2.0.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.fs-scheme" package depends on mocha@^2.5.3, which differs from the hoisted mocha@^3.4.2.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.import-notation" package depends on mocha@^3.2.0, which differs from the hoisted mocha@^3.4.2.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on mock-fs@^4.4.1, which differs from the more common mock-fs@^4.0.0.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.deps" package depends on mock-fs@^4.3.0, which differs from the hoisted mock-fs@^4.4.1.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.walk" package depends on mock-fs@^4.0.0, which differs from the hoisted mock-fs@^4.4.1.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on nyc@^11.0.3, which differs from the more common nyc@^10.0.0.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.deps" package depends on nyc@^6.4.4, which differs from the hoisted nyc@^11.0.3.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.entity-name" package depends on nyc@^10.0.0, which differs from the hoisted nyc@^11.0.3.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.naming" package depends on nyc@^10.0.0, which differs from the hoisted nyc@^11.0.3.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.walk" package depends on nyc@^10.0.0, which differs from the hoisted nyc@^11.0.3.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.fs-scheme" package depends on nyc@^10.1.2, which differs from the hoisted nyc@^11.0.3.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.import-notation" package depends on nyc@^10.1.2, which differs from the hoisted nyc@^11.0.3.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.graph" package depends on nyc@^6.6.1, which differs from the hoisted nyc@^11.0.3.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on proxyquire@^1.8.0, which differs from the more common proxyquire@^1.7.10.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.entity-name" package depends on proxyquire@^1.7.7, which differs from the hoisted proxyquire@^1.8.0.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.walk" package depends on proxyquire@^1.7.10, which differs from the hoisted proxyquire@^1.8.0.
lerna WARN EHOIST_ROOT_VERSION The repository root depends on sinon@^2.3.6, which differs from the more common sinon@^2.0.0.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.entity-name" package depends on sinon@^2.1.0, which differs from the hoisted sinon@^2.3.6.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.graph" package depends on sinon@^1.17.4, which differs from the hoisted sinon@^2.3.6.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.walk" package depends on sinon@^2.0.0, which differs from the hoisted sinon@^2.3.6.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.deps" package depends on ava@^0.15.0, which differs from the hoisted ava@^0.19.0.
lerna WARN EHOIST_PKG_VERSION "@bem/sdk.graph" package depends on ava@^0.15.2, which differs from the hoisted ava@^0.19.0.
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! execute Error: Command failed: npm install --global-style --force
lerna ERR! execute npm WARN using --force I sure hope you know what you are doing.
lerna ERR! execute npm ERR! Windows_NT 6.3.9600
lerna ERR! execute npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global-style" "--force"
lerna ERR! execute npm ERR! node v6.11.2
lerna ERR! execute npm ERR! npm  v3.10.10
lerna ERR! execute npm ERR! path C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz.3596098630
lerna ERR! execute npm ERR! code EPERM
lerna ERR! execute npm ERR! errno -4048
lerna ERR! execute npm ERR! syscall rename
lerna ERR! execute 
lerna ERR! execute npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz.3596098630' -> 'C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz'
lerna ERR! execute npm ERR!     at Error (native)
lerna ERR! execute npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz.3596098630' -> 'C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz'
lerna ERR! execute npm ERR!     at Error (native)
lerna ERR! execute npm ERR!   errno: -4048,
lerna ERR! execute npm ERR!   code: 'EPERM',
lerna ERR! execute npm ERR!   syscall: 'rename',
lerna ERR! execute npm ERR!   path: 'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz.3596098630',
lerna ERR! execute npm ERR!   dest: 'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz' }
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! Please try running this command again as root/Administrator.
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     C:\projects\bem-sdk\packages\deps\npm-debug.log
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (C:\projects\bem-sdk\node_modules\execa\index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm install --global-style --force
lerna ERR! execute npm WARN using --force I sure hope you know what you are doing.
lerna ERR! execute npm ERR! Windows_NT 6.3.9600
lerna ERR! execute npm ERR! argv "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--global-style" "--force"
lerna ERR! execute npm ERR! node v6.11.2
lerna ERR! execute npm ERR! npm  v3.10.10
lerna ERR! execute npm ERR! path C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz.3596098630
lerna ERR! execute npm ERR! code EPERM
lerna ERR! execute npm ERR! errno -4048
lerna ERR! execute npm ERR! syscall rename
lerna ERR! execute 
lerna ERR! execute npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz.3596098630' -> 'C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz'
lerna ERR! execute npm ERR!     at Error (native)
lerna ERR! execute npm ERR!  { Error: EPERM: operation not permitted, rename 'C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz.3596098630' -> 'C:\Users\appveyor\AppData\Roaming\npm-cache\nyc\6.6.1\package.tgz'
lerna ERR! execute npm ERR!     at Error (native)
lerna ERR! execute npm ERR!   errno: -4048,
lerna ERR! execute npm ERR!   code: 'EPERM',
lerna ERR! execute npm ERR!   syscall: 'rename',
lerna ERR! execute npm ERR!   path: 'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz.3596098630',
lerna ERR! execute npm ERR!   dest: 'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz' }
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! Please try running this command again as root/Administrator.
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     C:\projects\bem-sdk\packages\deps\npm-debug.log
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (C:\projects\bem-sdk\node_modules\execa\index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute   stack: 'Error: Command failed: npm install --global-style --force\nnpm WARN using --force I sure hope you know what you are doing.\nnpm ERR! Windows_NT 6.3.9600\nnpm ERR! argv "C:\\\\Program Files (x86)\\\\nodejs\\\\node.exe" "C:\\\\Program Files (x86)\\\\nodejs\\\\node_modules\\\\npm\\\\bin\\\\npm-cli.js" "install" "--global-style" "--force"\nnpm ERR! node v6.11.2\nnpm ERR! npm  v3.10.10\nnpm ERR! path C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz.3596098630\nnpm ERR! code EPERM\nnpm ERR! errno -4048\nnpm ERR! syscall rename\n\nnpm ERR! Error: EPERM: operation not permitted, rename \'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz.3596098630\' -> \'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz\'\nnpm ERR!     at Error (native)\nnpm ERR!  { Error: EPERM: operation not permitted, rename \'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz.3596098630\' -> \'C:\\Users\\appveyor\\AppData\\Roaming\\npm-cache\\nyc\\6.6.1\\package.tgz\'\nnpm ERR!     at Error (native)\nnpm ERR!   errno: -4048,\nnpm ERR!   code: \'EPERM\',\nnpm ERR!   syscall: \'rename\',\nnpm ERR!   path: \'C:\\\\Users\\\\appveyor\\\\AppData\\\\Roaming\\\\npm-cache\\\\nyc\\\\6.6.1\\\\package.tgz.3596098630\',\nnpm ERR!   dest: \'C:\\\\Users\\\\appveyor\\\\AppData\\\\Roaming\\\\npm-cache\\\\nyc\\\\6.6.1\\\\package.tgz\' }\nnpm ERR! \nnpm ERR! Please try running this command again as root/Administrator.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     C:\\projects\\bem-sdk\\packages\\deps\\npm-debug.log\n\n    at Promise.all.then.arr (C:\\projects\\bem-sdk\\node_modules\\execa\\index.js:210:11)\n    at process._tickCallback (internal/process/next_tick.js:109:7)',
```

**Comment by qfox** [comment]
Fixed

@Yeti-or thank you!
