### ISSUE TITLE
bemjson-to-decl падает, если bemjson содержит `null` или `undefined`

### ISSUE THREAD

**Issue by dima117** [bem/bem-sdk#230]
```js
var bemjsonToDecl = require('@bem/sdk.bemjson-to-decl');
var bemjson = [null];
var entities = bemjsonToDecl.convert(bemjson);
```

ошибка:
```
TypeError: Cannot read property 'block' of null
      at _getEntities (node_modules/@bem/sdk.bemjson-to-decl/index.js:30:17)
      at node_modules/@bem/sdk.bemjson-to-decl/index.js:19:31
      at Array.forEach (native)
      at _getEntities (node_modules/@bem/sdk.bemjson-to-decl/index.js:18:22)
      at Object.getEntities [as convert] (node_modules/@bem/sdk.bemjson-to-decl/index.js:69:12)
```

**Comment by qfox** [comment]
В decl/v1
```js
    it('should not throw on errored data. issue 230', () => {
        const input = cellify([null]);
        const output = [];

        expect(format(input, { format: 'v1' })).to.deep.equal(output);
    });
```
